- name: Make sure code extensions are available
  aur_build:
    name:
      - code-marketplace
      - code-features

- name: Make sure development tooling is installed
  community.general.pacman:
    name: 
      - posix
      - htop
      - code
      - code-marketplace
      - code-features
      - neovim
      - git
      - tig
      - firefox-developer-edition
      - alacritty
      - tmux
    state: present
    update_cache: yes
  become: yes

- name: Make sure vscode extensions are installed
  vscode_extension:
    name:
      - golang.go
      - rust-lang.rust
      - ms-python.vscode-pylance
      - ms-vscode.cpptools
      - arcticicestudio.nord-visual-studio-code
      - bradlc.vscode-tailwindcss

- name: Create directory for the alacritty config
  ansible.builtin.file:
    path: /home/charles/.config/alacritty/
    state: directory

- name: Copy alacritty config
  ansible.builtin.copy:
    src: alacritty.yml
    dest: /home/charles/.config/alacritty/alacritty.yml
    owner: charles
    group: charles
    mode: u=rw,g=r,o=r

- name: Make sure ops tooling is installed
  community.general.pacman:
    name: 
      - ansible
      - docker
      - docker-compose
      - whois
    state: present
  become: yes

- name: Add my user to docker group
  ansible.builtin.user:
    name: charles
    groups: docker
    append: yes
  become: yes

- name: Make sure docker daemon is started
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Make sure dev language & build tooling is installed
  community.general.pacman:
    name: 
      - rustup
      - arduino
      - cmake
      - go
      - ninja
      - nodejs
      - yarn
      - npm
      - mypy
      - maven
      - jdk8-openjdk
      - jdk11-openjdk
      - jdk-openjdk
    state: present
  become: yes

- name: Make sure teamviewer is available
  aur_build:
    name: 
      - teamviewer

- name: Make sure teamviewer is installed
  community.general.pacman:
    name: 
      - teamviewer
    update_cache: yes
    state: present
  become: yes

- name: Make sure intellij is available
  aur_build:
    name: 
      - intellij-idea-community-edition-jre

- name: Make sure intellij is installed
  community.general.pacman:
    name: 
      - intellij-idea-community-edition-jre
    update_cache: yes
    state: present
  become: yes