- name: Make sure gnome is installed
  community.general.pacman:
    name:
      - gnome
      - gdm
    state: present
  become: yes

- name: Make sure other gnome utils are installed
  community.general.pacman:
    name: gnome-tweaks
    state: present
  become: yes
  
- name: Make sure gnome is started
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: yes

- name: Make sure pulseaudio is removed
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-bluetooth
    state: absent
    extra_args: -dd # Skip dependency check because we really want to install pipewire
  become: yes

- name: Make sure desktop building blocks are installed
  community.general.pacman:
    name:
      - networkmanager
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      # Optional pipewire dependency
      - gst-plugin-pipewire
      # Optional pipewire dependency
      - pipewire-media-session
      # For screen sharing with pipewire
      - xdg-desktop-portal-gtk
    state: present
  become: yes

- name: Configure correct keyboard in gnomes
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'fr')]"
    state: present

- name: Use sane windows titlebar options
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
