- name: Make sure power saving tools are installed
  community.general.pacman:
    name:
      - tlp
      - acpi_call
      - ethtool
      - tp_smapi
    state: present
  become: yes

- name: Make sure tlp is started
  systemd:
    name: tlp
    state: started
    enabled: yes
  become: yes

- name: Add run_provision script for thinkpad t495
  ansible.builtin.template:
    src: provision.j2
    dest: /usr/local/bin/provision
    mode: '0755'
    owner: root
    group: root
  become: yes
  when: ansible_connection == 'local'
